
server:
  port: 5006
  servlet:
    session:
      cookie:
        http-only: true
  error:
    include-stacktrace: never

spring:
  application:
    name: helper-service
  devtools:
    restart:
      enabled: true
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/ipay?serverTimezone=Turkey&useSSL=false&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      format_sql: false

springdoc:
  swagger-ui:
    path: /docs


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:5001/eureka/





helper:
  message: Local

