
server:
  port: 5006
  servlet:
    session:
      cookie:
        http-only: true
  error:
    include-stacktrace: never

spring:
  # profiles:
  #   active: dev
  application:
    name: helper-service
  devtools:
    restart:
      enabled: true
  output:
    ansi:
      enabled: always


springdoc:
  swagger-ui:
    path: /docs


helper:
  message: Main msessage

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:5001/eureka/






