server:
  port: 5004
  servlet:
    session:
      cookie:
        http-only: true
  error:
    include-stacktrace: never


spring:
  profiles:
    active : ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: customer-service
  devtools:
    restart:
      enabled: true
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      format_sql: false
      

springdoc:
  swagger-ui:
    path: /docs


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://discover:5001/eureka/
