spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/ipay?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234


helper:
  message: Docker msessage

